name: CI and CD
on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set-Up Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm install
      - run: npm install react-scripts
      - run: npm run build
      - name: deploy
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with: 
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.CI_CD_DEPLOYMENT }}
