name: TESTING MERGE
on:
  pull_request:
    branches: 
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set-Up Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm install
      - run: npm install react-scripts
      - run: npm run build